### ISSUE TITLE
Koala Issue: Getting error Uncaught (in promise) 'pv_koala_init' failed with status INVALID_ARGUMENT

### ISSUE THREAD

**Issue by kirannatarajan** [Picovoice/koala#24]
### Expected behaviour
Koala library to get initialized correctly

### Actual behaviour
Getting error **Uncaught (in promise) 'pv_koala_init' failed with status INVALID_ARGUMENT**

### Steps to reproduce the behaviour
Followed steps as per the document
https://picovoice.ai/docs/quick-start/koala-web/

**Comment by kenarsa** [comment]
closing as you are providing no information for me to reproduce.
