### ISSUE TITLE
Picovoice Issue: Koala startup not working on Google Cloud Run

### ISSUE THREAD

**Issue by ajar98** [Picovoice/koala#27]
I've been able to run the Koala SDK locally, however when I deploy my code to Google Cloud Run, I get an `pvkoala._koala.KoalaInvalidArgumentError` when initializing the client - no other error message.

My Picovoice console says that I have 0/3 monthly active users, and I've successfully been able to run the SDK from multiple different machines (without the active users count increasing).

Do I need to be on the Developer plan for this? My username is `ai@vocode.dev`.

**Comment by kenarsa** [comment]
I think your `AccessKey` is not passed correctly to the engine. I would print it and make sure it is precisely the same. Running on Linux is fine. I am assuming you used `pip` for installing the package?

**Comment by ajar98** [comment]
I tried both `poetry` and `pip` for installation in case that changed something - will try to print the access key and get back to you - thank you!

**Comment by ajar98** [comment]
apologies! I had extraneous quotes `"` in my environment variable - works as expected :)
