### ISSUE TITLE
Would love a flutter plugin for Koala

### ISSUE THREAD

**Issue by masonjeffreys** [Picovoice/koala#31]
I use Porcupine and Rhino in a flutter app and would love to add Koala to improve the speech recognition for both the wake word and the speech-to-intent.
Is there a Flutter Koala plugin in the works?
Thanks!
Jeff

**Comment by ksyeo1010** [comment]
Unfortunately, this is not in the road map. If this is a commercial application with the budget allocated, feel free to contact the [sales team](https://picovoice.ai/pricing/).
