### ISSUE TITLE
Picovoice Documentation Issue (/docs/koala/)

### ISSUE THREAD

**Issue by nwsirlp** [Picovoice/koala#64]
`import { KoalaWorker } from "@picovoice/koala-web";
import koalaParams from "${KOALA_PARAMS_BASE64_PATH}";

function processCallback(enhancedPcm: Int16Array) {
  // do something with enhancedPcm
}

const koala = await KoalaWorker.create(
  "${ACCESS_KEY}",
  processCallback,
  {
    base64: koalaParams,
    // or
    publicPath: "${MODEL_RELATIVE_PATH}",
  }
);
`
I try to using koala but where is MODEL_RELATIVE_PATH or KOALA_PARAMS_BASE64_PATH and Is there no callback func process? I just want to use koala with audio context. to using model turing voice recognize input from microphone (React)

**Comment by ErisMik** [comment]
Can you please reopen using the [issue template](https://github.com/Picovoice/koala/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Koala+Issue%3A+), then I will be able to assist you.

**Comment by nwsirlp** [comment]
> Can you please reopen using the [issue template](https://github.com/Picovoice/koala/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=Koala+Issue%3A+), then I will be able to assist you.

Ok, thank you
