### ISSUE TITLE
using  Picovoice Koala on the ARM architecture ARM11

### ISSUE THREAD

**Issue by bmt1596** [Picovoice/koala#9]
Hello Picovoice team,

I am interested in using Picovoice Koala on the ARM architecture ARM11. I noticed that the current version of Koala only supports Raspberry Pi 3 and 4, and I was wondering if you have plans to add ARM11 support in the future. Additionally, if I would like to experience Picovoice immediately on ARM11, is there any way to do so? Thank you for your help and guidance.

**Comment by mrrostam** [comment]
Hi @bmt1596 

Unfortunately this is not on the roadmap. If your inquiry is for a commercial application that justifies the effort you can submit a sales inquiry and we can look into it.

**Comment by bmt1596** [comment]
thank you for the reply, i tried searching contact to contact sales but only found Dev & Pilot item and this requires placing an order. We just want to confirm that Koala is working fine on our Board including parameters (CPU-Requiment, Performace after signal processing) before making a decision to buy a license from you. Is there a way for me to get a Test-Version for ARM11.

**Comment by bmt1596** [comment]
Currently, as far as I can see, you only support email for customers who have purchased the product, or purchasing a license is required before we can confirm the performance of Koala picovoice.  Where should I email a support request. I look forward to your reply, thanks.

**Comment by bmt1596** [comment]
Thank you very much I will send an email to them.
